name: Deploy to Main Branch

on:
  push:
    branches:
      - main

jobs:
  deploy-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: List files in the directory
        run: ls -al

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Verify SSH Key Exists
        run: |
          if [ ! -f ~/.ssh/id_rsa ]; then
            echo "SSH key does not exist"
            exit 1
          fi

      - name: Debug SSH Connection
        run: |
          ssh -vvv -i ~/.ssh/id_rsa id_rsa@${{ secrets.SERVER_HOST }} exit

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ./ansible/inventory ./deploy-server.yml --private-key ~/.ssh/id_rsa
